services:
  auctions:
    container_name: auctions_django
    build: .
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8001"
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./:/auctions
    env_file:
      - .env
    depends_on:
      - postgres
      - auctions_redis
    networks:
      - micro-network

  postgres:
    container_name: auctions_postgres
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5433"

  auctions_redis:
    container_name: auctions_redis
    image: redis:alpine
    restart: always
    ports:
      - "6380:6380"

volumes:
  postgres_data:

networks:
  micro-network:
    external: true
