services:
  auctions:
    container_name: auctions_django
    build: .
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py makemessages -l ka &&
             python3 manage.py compilemessages -l ka &&
             python3 manage.py runserver 0.0.0.0:8001"
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./:/auctions
    env_file:
      - .env
    depends_on:
      - auctions_postgres
      - auctions_redis
#      - consumer_command
    networks:
      - micro-network
      - auctions-private-network

  auctions_postgres:
    container_name: auctions_postgres
    image: postgres:16
    restart: always
    volumes:
      - postgres_auctions_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - auctions-private-network

  auctions_redis:
    container_name: auctions_redis
    image: redis:alpine
    restart: always
    ports:
      - "6380:6379"
    networks:
      - auctions-private-network

#  consumer_command:
#    container_name: auctions_consumer_command
#    restart: always
#    build: .
#    command: python3 manage.py rabbit_command
#    env_file:
#      - ./.env
#    networks:
#      - auctions-private-network

volumes:
  postgres_auctions_data:

networks:
  micro-network:
    external: true
  auctions-private-network:
    external: false
