[tool.black]
line-length = 90
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
/(
    migrations            # Exclude Django migrations
    | migrations/.*       # Exclude all files within any migrations directory
    | __pycache__         # Exclude __pycache__
    | \.git               # Exclude the .git directory
    | \.venv              # Exclude virtual environments
    | \.eggs              # Exclude .eggs directories
    | \.egg-info          # Exclude .egg-info directories
    | \.tox               # Exclude .tox directories
    | dist                # Exclude distribution directories
    | build               # Exclude build directories
    | docs                # Exclude documentation directories
)/
'''

[tool.isort]
profile = "black"
