# Generated by Django 5.0.7 on 2024-09-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Electronics", "Electronics"),
                            (
                                "Clothing, Shoes & Accessories",
                                "Clothing, Shoes & Accessories",
                            ),
                            ("Sporting Goods", "Sporting Goods"),
                            ("Toys & Hobbies", "Toys & Hobbies"),
                            ("Home & Garden", "Home & Garden"),
                            ("Jewelry & Watches", "Jewelry & Watches"),
                            ("Health & Beauty", "Health & Beauty"),
                            ("Business & Industrial", "Business & Industrial"),
                            ("Baby Essentials", "Baby Essentials"),
                            ("Pet Supplies", "Pet Supplies"),
                            ("Books, Movies & Music", "Books, Movies & Music"),
                            ("Collectibles & Art", "Collectibles & Art"),
                            (
                                "Vehicle Parts & Accessories",
                                "Vehicle Parts & Accessories",
                            ),
                            ("Musical Instruments & Gear", "Musical Instruments & Gear"),
                            ("Major Appliances", "Major Appliances"),
                            ("Camping & Hiking", "Camping & Hiking"),
                            ("Automotive", "Automotive"),
                            ("Real Estate", "Real Estate"),
                            ("Furniture", "Furniture"),
                            ("Food & Beverages", "Food & Beverages"),
                            ("Office Supplies", "Office Supplies"),
                            ("Surveillance & Security", "Surveillance & Security"),
                            ("Bicycles & Accessories", "Bicycles & Accessories"),
                            ("Video Games & Consoles", "Video Games & Consoles"),
                            ("Crafts", "Crafts"),
                            ("Antiques", "Antiques"),
                            ("Fishing & Boating", "Fishing & Boating"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
