# Generated by Django 5.0.7 on 2024-09-29 15:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0002_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author", models.UUIDField()),
                ("auction_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("max_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "accepted_bidders",
                    models.CharField(
                        choices=[
                            ("Company", "Company"),
                            ("Individual", "Individual"),
                            ("Both", "Both"),
                        ],
                        default="Both",
                        max_length=20,
                    ),
                ),
                (
                    "accepted_locations",
                    models.CharField(
                        choices=[
                            ("My Location", "My Location"),
                            ("International", "International"),
                        ],
                        default="My Location",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Live", "Live"),
                            ("Draft", "Draft"),
                            ("Completed", "Completed"),
                            ("Canceled", "Canceled"),
                            ("Deleted", "Deleted"),
                        ],
                        default="Draft",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("GEL", "GEL"), ("USD", "USD"), ("EUR", "EUR")],
                        default="GEL",
                        max_length=3,
                    ),
                ),
                ("custom_fields", models.JSONField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Used - Like New", "Used - Like New"),
                            ("Used - Very Good", "Used - Very Good"),
                            ("Used - Good", "Used - Good"),
                            ("Used - Acceptable", "Used - Acceptable"),
                        ],
                        default="New",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="auction.category"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(related_name="auctions", to="auction.tag"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Auction Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Auction Updated At"
                    ),
                ),
            ],
        ),
    ]
