# Generated by Django 5.0.7 on 2024-10-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0007_alter_auction_accepted_locations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auction",
            options={"ordering": ["-created_at"]},
        ),
    ]
