# Generated by Django 5.0.7 on 2024-10-04 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0008_alter_auction_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="bookmark",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Bookmark Created At",
            ),
            preserve_default=False,
        ),
    ]
