# Generated by Django 5.0.7 on 2024-10-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0008_alter_auction_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter a detailed description of the bid",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BidImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="URL of the uploaded image", null=True
                    ),
                ),
                (
                    "bid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="auction.bid",
                    ),
                ),
            ],
        ),
    ]
