# Generated by Django 5.0.7 on 2024-10-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0009_bid_bidimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="delivery_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Enter the delivery fee for the bid",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="pending",
                help_text="Status of the bid",
            ),
        ),
    ]
