# Generated by Django 5.0.7 on 2024-10-21 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0009_alter_bookmark_options_bookmark_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winner_bid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("winner_bid_author", models.UUIDField(blank=True, null=True)),
                (
                    "top_bid",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("top_bid_author", models.UUIDField(blank=True, null=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("total_bids_count", models.PositiveIntegerField(default=0)),
                (
                    "auction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="auction.auction",
                    ),
                ),
            ],
        ),
    ]
