# Generated by Django 5.0.7 on 2024-10-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0010_auctionstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="author_avatar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="author_kyc_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auction",
            name="author_nickname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
