# Generated by Django 5.0.7 on 2024-10-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0011_auction_author_avatar_auction_author_kyc_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionstatistics",
            name="bookmarks_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
