# Generated by Django 5.0.7 on 2024-11-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0013_auction_auction_auc_author_8c26f5_idx_and_more"),
        ("bid", "0004_alter_bid_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionstatistics",
            name="top_bid_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="top_bid_statistics",
                to="bid.bid",
            ),
        ),
        migrations.AddField(
            model_name="auctionstatistics",
            name="winner_bid_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winner_bid_statistics",
                to="bid.bid",
            ),
        ),
    ]
