# Generated by Django 5.0.7 on 2024-10-17 12:40

import uuid

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auction", "0009_alter_bookmark_options_bookmark_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author", models.UUIDField()),
                ("offer", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter a detailed description of the bid",
                        null=True,
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Enter the delivery fee for the bid",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Deleted", "Deleted"),
                        ],
                        default="Pending",
                        help_text="Status of the bid",
                        max_length=20,
                    ),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="auction.auction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BidImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3.S3Storage(
                            bucket_name="reversello-bid-images",
                            location="bid_images",
                            object_parameters={"CacheControl": "max-age=86400"},
                            querystring_auth=False,
                            region_name="eu-central-1",
                        ),
                        upload_to="",
                        verbose_name="Bid Image",
                    ),
                ),
                (
                    "bid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="bid.bid",
                    ),
                ),
            ],
        ),
    ]
