# Generated by Django 5.0.7 on 2024-10-17 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0009_alter_bookmark_options_bookmark_created_at"),
        ("bid", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="auction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auction.auction",
            ),
        ),
    ]
