# Generated by Django 5.0.7 on 2024-10-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bid", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="author_avatar",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="author_kyc_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bid",
            name="author_nickname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
