# Generated by Django 5.0.7 on 2024-11-01 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bid", "0002_bid_author_avatar_bid_author_kyc_verified_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="bid",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Bid Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Bid Updated At"),
        ),
    ]
