# Generated by Django 5.0.7 on 2024-11-03 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bid", "0003_alter_bid_options_bid_created_at_bid_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={"ordering": ["offer", "-updated_at", "-created_at"]},
        ),
    ]
