# Generated by Django 5.0.7 on 2024-11-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0014_auctionstatistics_top_bid_object_and_more"),
        ("bid", "0005_alter_bid_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["auction", "created_at", "id"], name="idx_bid_auction_created"
            ),
        ),
    ]
